AWSTemplateFormatVersion: "2010-09-09"
Description: 3M HealthEquip Manager Stack CloudFormation Template

Parameters:
  DBUsername:
    Type: String
    Default: "healthequip_admin"
    Description: "RDS DB Username"
  DBPassword:
    Type: String
    Default: "healthequip_password"
    Description: "RDS DB Password"
  DBIdentifier:
    Type: String
    Default: "healthequip-mysql-db"
    Description: "RDS DB Identifier"
  DBName:
    Type: String
    Default: "healthequipdb"

Resources:

  # Provision the RDS (MSSQL) db instance
  RDSDatabaseInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      Engine: "mysql"
      EngineVersion: "8.0"
      LicenseModel: "general-public-license"
      DBInstanceClass: "db.t2.micro"
      AllocatedStorage: "20"
      AllowMajorVersionUpgrade: "true"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceIdentifier: !Ref DBIdentifier
      DBName: !Ref DBName

Outputs:
  RDSEndpoint:
    Description: "Endpoint of the HealthEquip RDS database instance"
    Value: !GetAtt RDSDatabaseInstance.Endpoint.Address
  RDSName:
    Description: "Name of the HealthEquip RDS database"
    Value: !Ref DBName
